# Generated by Django 4.2.3 on 2023-11-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('datos_especificos', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParteLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('parte_leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.parteleccion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenDGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.leccion')),
                ('preguntas', models.ManyToManyField(to='Lessons.ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='parte_leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.parteleccion'),
        ),
    ]
