# Generated by Django 4.2.3 on 2023-11-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='descripcion',
            field=models.CharField(default='Descripción predeterminada', max_length=150),
        ),
        migrations.AddField(
            model_name='parteleccion',
            name='descripcion',
            field=models.CharField(default='Descripción predeterminada', max_length=100),
        ),
        migrations.AlterField(
            model_name='examendgt',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.parteleccion'),
        ),
    ]
