# Generated by Django 4.2.3 on 2023-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0003_definicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definicion',
            name='clave',
            field=models.TextField(),
        ),
    ]
