# Generated by Django 4.2.3 on 2023-11-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0004_alter_definicion_clave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Definicion',
            new_name='Definicions',
        ),
    ]
