# Generated by Django 4.2.7 on 2023-11-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0006_conceptos_delete_definicions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conceptos',
            new_name='Concepto',
        ),
    ]
