# Generated by Django 4.2.7 on 2023-11-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0007_rename_conceptos_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto',
            name='nota',
            field=models.TextField(default='no hay nota', max_length=300),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='parte_leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.leccion'),
        ),
    ]
