# Generated by Django 4.2.7 on 2023-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0008_alter_concepto_nota_alter_ejercicio_parte_leccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='tipos_ejercicio_validos',
            field=models.ManyToManyField(to='Lessons.ejercicio'),
        ),
    ]
