# Generated by Django 4.2.7 on 2023-11-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0009_concepto_tipos_ejercicio_validos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='partes_leccion_validas',
            field=models.ManyToManyField(related_name='ejercicios_validos', to='Lessons.parteleccion'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='parte_leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lessons.parteleccion'),
        ),
    ]
